server:
  contextPath: /api
  session:
    timeout: 1800

spring:
  datasource:
    continue-on-error: true
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat: 
      maxActive: 10
      initialSize: 2
      maxIdle: 4
      minIdle: 2
      testOnBorrow: true
      testOnConnect: true
      validationQuery: SELECT 1 FROM DUAL
      initSQL: SELECT 1 FROM DUAL
      jdbcInterceptors: ConnectionState;StatementFinalizer;ResetAbandonedTimer    
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  
  jpa:
    hibernate:
      ddl-auto: none

ldap:
  url: ${LDAP_URL}
  domain: ${LDAP_DOMAIN}
  domainAlias: ${LDAP_DOMAIN_ALIAS}
  login_form: false

liquibase:
  change-log: classpath:/db/changelog-master.xml

---
spring: 
  profiles: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat: 
      validationQuery: SELECT 1
      initSQL: SELECT 1
    url: jdbc:postgresql://localhost:5432/parking

---
spring:
  profiles: development

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: parking
    password: parking

ldap:
  url: ldap://dc-sl01.cwinet.local:3268
  domain: cwinet.local
  domainAlias: cwi.com.br
  
logging: 
  level:
    parking: trace
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
